# Site settings
title: ^_^ Lovely Photography ^_^
description: Elegant, Golden, Masterpiece Photo Here!
keywords: Modern, Blogging, Fun
author: ANMILD^95
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://anmild95.github.io/Lovely_blog/" # the base hostname & protocol for your site
